# Generated by Django 2.1.1 on 2018-12-02 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageaccounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('check_id', models.AutoField(primary_key=True, serialize=False)),
                ('written_date', models.DateTimeField(verbose_name='date written')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('check_no', models.PositiveIntegerField(verbose_name='check number')),
                ('recipient', models.TextField(verbose_name='recipient')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageaccounts.Account')),
            ],
        ),
    ]
