# Generated by Django 2.1.1 on 2018-09-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('written_date', models.DateTimeField(verbose_name='date written')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('routing_no', models.PositiveIntegerField(verbose_name='routing number')),
                ('account_no', models.PositiveIntegerField(verbose_name='account number')),
                ('check_no', models.PositiveIntegerField(verbose_name='check number')),
            ],
        ),
    ]
