# Generated by Django 2.1.1 on 2018-09-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managechecks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='id',
        ),
        migrations.AddField(
            model_name='check',
            name='check_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
