# Generated by Django 2.1.1 on 2018-12-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managechecks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='recipient',
            field=models.CharField(max_length=250),
        ),
    ]
