# Generated by Django 2.1.1 on 2018-12-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageaccounts', '0003_auto_20181201_1432'),
        ('manageaccounts', '0003_auto_20181129_1031'),
    ]

    operations = [
    ]
